resources:
  - repo: self
trigger: ["*"]
jobs:
  - job: DockerPhase
    displayName: Docker
    condition: succeeded()
    pool: 
      name: Azure Pipelines
      vmImage: ubuntu-16.04
    variables:
      - name: ContainerImageName
        value: "vh-web-docs"
      - name: RegistryName
        value: "vhprodacr.azurecr.io"
      - name: ContainerTag
        value: $(Build.SourceVersion)
      - name: SonarCloudPROptions
        value: " " #Default value for when not building a PR
      - name: DockerBuildArgs
        value: " " # Default value
      - group: SonarCloud
    steps:
      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: "Replace tokens in Dockerfile"
        inputs:
          targetFiles: "**/Dockerfile"
          keepToken: true

      - task: Docker@1
        displayName: "Build an image"
        inputs:
          azureSubscriptionEndpoint: 'vh-prod (239a4b13-139c-4213-b7b6-2de75f88468d)'
          azureContainerRegistry: '{"loginServer":"vhprodacr.azurecr.io", "id" : "/subscriptions/239a4b13-139c-4213-b7b6-2de75f88468d/resourceGroups/vh-prod-rg/providers/Microsoft.ContainerRegistry/registries/vhprodacr"}'
          imageName: "$(ContainerImageName):$(ContainerTag)"
          includeSourceTags: true
          arguments: "$(DockerBuildArgs)"

      - task: Docker@1
        displayName: "Push an image"
        inputs:
          azureSubscriptionEndpoint: 'vh-prod (239a4b13-139c-4213-b7b6-2de75f88468d)'
          azureContainerRegistry: '{"loginServer":"vhprodacr.azurecr.io", "id" : "/subscriptions/239a4b13-139c-4213-b7b6-2de75f88468d/resourceGroups/vh-prod-rg/providers/Microsoft.ContainerRegistry/registries/vhprodacr"}'
          command: "Push an image"
          imageName: "$(ContainerImageName):$(ContainerTag)"
          includeSourceTags: true
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: "Replace tokens in **/*.ci.yaml and **/*.ci.env"
        inputs:
          targetFiles: "**/*.ci.yaml,**/*.ci.env"
          keepToken: true

      - task: CopyFiles@2
        displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
        inputs:
          Contents: |
            **/*.ci.yaml
            **/*.ci.env
          TargetFolder: "$(Build.ArtifactStagingDirectory)"
          flattenFolders: true

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: drop"
