site_name: VendorHub Docs
site_url: https://www.vendorhub.io
site_description: Project documentation with Markdown.
site_author: VendorHub Team

repo_name: 'rixian/vh-docs'
repo_url: https://github.com/rixian/vh-docs/
edit_uri: "blob/master/src/docs/"

# Copyright
copyright: 'Copyright &copy; Rixian LLC'

theme:
  name: 'material'
  logo: 'images/logo_white.png'
  favicon: 'images/favicon.ico'
  palette:
    scheme: default # slate
  features:
    - tabs

nav:
    - Home: index.md
    #- Forms: 
    #    - Overview: forms/overview.md
    - 'Libraries':
        - 'About Libraries': libraries/overview.md
        - Architecture: 'libraries/architecture.md'
        - Features: 
            - 'Overview': libraries/features.md
            - 'Multi Tenant': libraries/multi_tenant.md
            - 'Bring-Your-Own-Storage': libraries/byos.md
            - 'Indexing': libraries/indexing.md
            - 'SFTP Server': libraries/sftp_server.md
            - 'Anti-Virus Scanning': libraries/anti_virus.md
            - 'Tagging': libraries/tagging.md
            - 'Searching': libraries/searching.md
            - 'Alternate Streams': libraries/alternate_streams.md
            - 'Dashboard': libraries/dashboard.md
        - 'Getting Started': libraries/getting_started.md
        - 'Libraries SDK': 
          - Overview: 'libraries/sdk/overview.md'
          - Reference:
            - ListLibraries: 'libraries/sdk/list_libraries.md'
    - 'Api Reference':
        - Overview: Overview.md
        - Authentication: apis/auth.md
        - Paths in VendorHub: apis/paths.md
        #- 'Forms': 
        #    - 'List Forms': apis/forms/list_forms.md
        - 'Document Library': 
            - 'List Libraries': apis/libraries/list_libraries.md
            - 'Create Library': apis/libraries/create_library.md
            - 'Get Library': apis/libraries/get_library.md
            - 'Search': apis/libraries/search_library.md
            - 'Download': apis/libraries/download.md
            - 'Get Info': apis/libraries/get_item.md
            - 'Delete': apis/libraries/delete_item.md
            - 'List Children': apis/libraries/list_children.md
            - 'Exists': apis/libraries/exists.md
            - 'Copy': apis/libraries/copy.md
            - 'Move': apis/libraries/move.md            
            - 'List Tags': apis/libraries/list_file_tags.md
            - 'Upsert Tags': apis/libraries/upsert_file_tags.md
            - 'Clear Tags': apis/libraries/clear_file_tags.md
            - 'Remove Tag': apis/libraries/remove_file_tag.md
plugins:
  - search:
      lang:
        - en
extra:
  search:
    language: 'en'
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'
  - 'javascript/extra.js'
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  #- pymdownx.md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs/icons
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path: docs
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde